import LegalLayout from '@/components/LegalLayout';

export const metadata = { title: 'Privacy Policy — Shopron' };

export default function PrivacyPolicyPage(){
  return (
    <LegalLayout>
      <h2>1. Introduction</h2>
      <p>Welcome to Shopron. Shopron (&quot;us&quot;, &quot;we&quot;, or &quot;our&quot;) operates www.shopron.com (the &quot;Service&quot;). This Privacy Policy governs your visit to www.shopron.com and explains how we collect, safeguard and disclose information that results from your use of our Service. We use your data to provide and improve our Service. By using the Service, you agree to the collection and use of information in accordance with this policy.</p>

      <h2>2. Definitions</h2>
      <p><strong>Personal Data</strong> means data about a living individual who can be identified from that data. <strong>Usage Data</strong> is data collected automatically, generated by use of the Service or from Service infrastructure (e.g. the duration of a page visit). <strong>Cookies</strong> are small files stored on your device. We act as the <strong>Data Controller</strong> of your data; any third party we use to process data on our behalf is a <strong>Data Processor</strong>.</p>

      <h2>3. Types of Data Collected</h2>
      <p><strong>Personal Data</strong> — while using our Service we may ask for personally identifiable information, including but not limited to: email address, first and last name, phone number, address, country, state, ZIP/postal code, city, and cookies/usage data. We may use your data to contact you with newsletters or promotional materials; you may opt out via the unsubscribe link at any time.</p>
      <p><strong>Usage Data</strong> — we may collect information your browser sends when you visit our Service, such as IP address, browser type and version, pages visited, time and date of visit, time spent on pages, and other diagnostic data.</p>
      <p><strong>Tracking Cookie Data</strong> — we use cookies and similar technologies (session, preference, security and advertising cookies) to operate and improve the Service. You can instruct your browser to refuse cookies, though some portions of the Service may not function without them.</p>

      <h2>4. Use of Data</h2>
      <ul>
        <li>To provide and maintain our Service</li>
        <li>To notify you about changes to our Service</li>
        <li>To provide customer support</li>
        <li>To gather analysis so we can improve our Service</li>
        <li>To detect, prevent and address technical issues</li>
        <li>To fulfil obligations arising from any contract entered into between you and us, including billing</li>
        <li>To provide news, offers and general information about goods and services similar to those you have purchased, unless you opt out</li>
      </ul>

      <h2>5. Retention &amp; Transfer of Data</h2>
      <p>We retain Personal Data only as long as necessary for the purposes set out in this Policy, or as required to comply with legal obligations, resolve disputes and enforce our agreements. Your information may be transferred to and maintained on computers located outside your state or country, where data protection laws may differ. Your consent to this Policy represents your agreement to that transfer.</p>

      <h2>6. Disclosure of Data</h2>
      <p>We may disclose Personal Data if required by law or in response to valid requests by public authorities, in connection with a business transaction (merger, acquisition or asset sale), or to our subsidiaries, affiliates and service providers who support our business, subject to confidentiality obligations.</p>

      <h2>7. Security of Data</h2>
      <p>The security of your data matters to us, but no method of transmission over the Internet or electronic storage is 100% secure. While we use commercially acceptable means to protect your Personal Data, we cannot guarantee absolute security.</p>

      <h2>8. Your Data Protection Rights (GDPR)</h2>
      <p>Although Shopron ships only within the United States, visitors from the EU/EEA are protected by GDPR. You have the right to access, rectify, erase, restrict processing of, port, or object to processing of your personal data, and to withdraw consent at any time. To exercise these rights, contact us at <strong>support@shopron.shop</strong> — we respond within 30 days.</p>

      <h2>9. California Privacy Rights (CalOPPA &amp; CCPA)</h2>
      <p>California residents may request the categories and specific pieces of personal information we hold, ask us to delete that information, and opt out of any sale of personal information. We do not sell personal information for monetary consideration. We honor &quot;Do Not Track&quot; browser signals. To exercise these rights, email <strong>support@shopron.shop</strong>.</p>

      <h2>10. Service Providers, Analytics &amp; Payments</h2>
      <p>We may employ third-party companies to facilitate our Service, monitor usage, or automate development. We do not store your payment card details — that information is provided directly to our PCI-DSS compliant third-party payment processors.</p>

      <h2>11. Links to Other Sites &amp; Children&apos;s Privacy</h2>
      <p>Our Service may link to third-party sites not operated by us; we assume no responsibility for their content or privacy practices. Our Service is not intended for use by anyone under 18, and we do not knowingly collect data from children.</p>

      <h2>12. Changes to This Policy</h2>
      <p>We may update this Privacy Policy from time to time. Changes are effective when posted on this page, and material changes will be communicated via email or a prominent notice on the Service.</p>

      <h2>13. Contact Us</h2>
      <p>If you have any questions about this Privacy Policy, please contact us:<br />
      Phone: +1 888-556-2111<br />
      Email: support@shopron.shop<br />
      Address: 6890 Distribution Dr, Beltsville, MD 20705, United States</p>
    </LegalLayout>
  );
}
